
export default {
    classRoster: 'Round',
    viewOnGitHub: 'View on GitHub',
    tagline: 'A fun way to encourage classroom participation.',
    yearsOld: 'years old',
    aiConfig: {
      title: 'Challenge Configuration',
      challengeConfigDescription: 'Set the context for the next challenge generated by the AI.',
      ageOrGrade: 'Age or Grade',
      ageOrGradePlaceholder: 'e.g., 8 years old, 3rd Grade',
      country: 'Country',
      countryPlaceholder: 'e.g., USA, Chile',
      customPrompt: 'Custom Prompt',
      customPromptPlaceholder: 'e.g., Focus on collaboration',
      negativePrompt: 'Negative Prompt',
      negativePromptPlaceholder: 'e.g., Avoid math problems',
      subject: 'Subject',
      subjectPlaceholder: 'Select a subject',
      spotlight: {
        title: 'Spotlight',
        atDesk: 'Cozy Corner',
        inFront: 'Center Stage',
        doesNotMatter: "Doesn't Matter",
      },
      model: {
        title: 'AI Model',
        placeholder: 'Select a model...',
        customPlaceholder: 'Custom model'
      },
      ollamaBaseUrl: {
        title: 'Ollama Base URL',
        placeholder: 'e.g., http://localhost:11434'
      },
      saveButton: 'Save Configuration',
      toastSaved: 'AI configuration saved!',
      toastError: 'Failed to save AI configuration.',
      plugin: {
        title: 'Plugin',
        placeholder: 'Select a plugin...',
      }
    },
  } as const;
