

import { ActivityAdaptation } from "../../domain/activity-adaptation.entity";

export type CreateActivityAdaptationDTO = Partial<Omit<ActivityAdaptation, 'id' | 'createdAt' | 'updatedAt' | 'suggestions'>> & {
    originalActivity: string;
    suggestions: any[]; // Kept for compatibility, but will be generated by the service
    studentNeeds?: string[];
    classInterests?: string[];
    customPrompt?: string;
};
