'use server';

import { config } from 'dotenv';
config();

// Bootstrap all application modules and dependencies
import { initializeServices } from '@/services/bootstrap';
initializeServices();

// Import AI flows
import '@/ai/flows/generate-lightning-round.ts';
import '@/ai/flows/generate-student-challenge.ts';
import '@/ai/flows/generate-prompt-suggestion.ts';
import '@/ai/flows/generate-student-profile-suggestion.ts';
import '@/ai/flows/generate-coach-suggestion.ts';
import '@/ai/flows/generate-support-plan.ts';
import '@/ai/flows/generate-mood-analysis.ts';
import '@/ai/flows/generate-qualities-suggestion.ts';
import '@/ai/flows/generate-concern-analysis.ts';
import '@/ai/flows/generate-curriculum-activities.ts';
import '@/ai/flows/generate-group-curriculum-activities.ts';
import '@/ai/flows/generate-personalized-activity.ts';
import '@/ai/flows/generate-activity-suggestions.ts';
import '@/ai/flows/generate-group-activity-suggestion.ts';
import '@/ai/flows/generate-fear-management-suggestion.ts';
import '@/ai/flows/generate-fear-update-suggestion.ts';
import '@/ai/flows/generate-activity-adaptation.ts';
import '@/ai/flows/generate-rubric.ts';
import '@/ai/flows/generate-language-support.ts';
import '@/ai/flows/generate-riddle-battle.ts';
import '@/ai/flows/generate-story-chapter.ts';
import '@/ai/flows/generate-final-chapter.ts';
import '@/ai/flows/generate-story-starters.ts';
import '@/ai/flows/generate-story-contribution-suggestion.ts';
import '@/ai/flows/generate-test-from-story.ts';
import '@/ai/flows/generate-test-from-topic.ts';
import '@/ai/flows/generate-relationship-remediation.ts';
import '@/ai/flows/generate-relationship-suggestion.ts';
import '@/ai/flows/generate-observation-analysis.ts';
import '@/ai/flows/generate-improved-observation.ts';
import '@/ai/flows/generate-story-illustration.ts';
import '@/ai/flows/generate-speech-from-text.ts';
import '@/ai/flows/generate-multi-speaker-speech.ts';
import '@/ai/flows/generate-individual-relationship-strategy.ts';
import '@/ai/flows/generate-adjusted-individual-strategy.ts';
import '@/ai/flows/generate-expert-advice.ts';
import '@/ai/flows/generate-skill-suggestion.ts';
import '@/ai/flows/generate-activity-summary.ts';
import '@/ai/flows/generate-test-analysis.ts';
import '@/ai/flows/generate-debate.ts';
import '@/ai/flows/generate-debate-topic-suggestion.ts';
import '@/ai/flows/generate-digital-conviviality-activity.ts';
import '@/ai/flows/generate-digital-conflict-scenario.ts';
import '@/ai/flows/generate-digital-pact.ts';
import '@/ai/flows/generate-activity-topic-suggestion.ts';
import '@/ai/flows/generate-pbl-project.ts';
import '@/ai/flows/generate-pbl-teams.ts';
import '@/ai/flows/generate-pbl-scaffolding.ts';
import '@/ai/flows/generate-safety-risk-map.ts';
import '@/ai/flows/generate-safety-protocol.ts';
import '@/ai/flows/generate-crisis-scenario.ts';
import '@/ai/flows/generate-safety-brigade.ts';
import '@/ai/flows/generate-safety-role-suggestion.ts';
import '@/ai/flows/generate-classroom-pulse.ts';
import '@/ai/flows/generate-pedagogical-menu.ts';
import '@/ai/flows/generate-classroom-climate-scenario.ts';
import '@/ai/flows/generate-question-analysis.ts';
import '@/ai/flows/generate-reflection-guidance.ts';
import '@/ai/flows/generate-class-analysis-from-audio.ts';
import '@/ai/flows/mbe-indexer.ts';
import '@/ai/flows/mbe-consultation.ts';
